#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/task.h"

#include "sdkconfig.h" // generated by "make menuconfig"

#include "bme280.h"

void i2c_master_init();
//static s8 BME280_I2C_bus_write(u8 dev_addr, u8 reg_addr, u8 *reg_data, u8 cnt);
//static s8 BME280_I2C_bus_read(u8 dev_addr, u8 reg_addr, u8 *reg_data, u8 cnt);
//static void BME280_delay_msek(u32 msek);
void task_bme280_normal_mode(void *ignore);

double get_mBME280_Temp();
double get_mBME280_Hum();
double get_mBME280_Press();

